version: '3.3'

services: 
    mysqldb:
        image: mysql:5.7
        restart: always
        env_file: ./.env
        ports: 
            - "3306:3306"
        networks: 
            - app-network
        volumes: 
            - ./docker-db/my.cnf:/etc/mysql/my.cnf
    
    app:
        build: 
            context: .
            dockerfile: ./Dockerfile
        depends_on: 
            - mysqldb
        tty: true
        ports: 
            - "3000:3000"
        # command: npx sequelize-cli db:migrate
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge
    
