version: '3.3'

services: 
    mysqldb:
        image: mysql:5.7
        restart: always
        env_file: ./.env
        environment: 
            - WAIT_HOSTS=mysql:3306
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
        networks: 
            - app-network
    
    migration:
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: app-image
        depends_on:
            - mysqldb
        tty: true
        command: ["./wait-for-it/wait-for-it.sh", "mysqldb:3306", "--", "npm", "run", "migrate"]
        networks: 
            - app-network

    app:
        image: app-image 
        ports: 
            - "3000:3000"
        networks: 
            - app-network
        depends_on: 
            - mysqldb
            - migration
        command: npm run start
        volumes: 
            - "./log:/log"

networks: 
    app-network:
        driver: bridge
    
